//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by H1EUSB_SampleApp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_COMOPEN                     102
#define IDS_ERR_COMOPEN                 103
#define IDS_SEND_TEMPLATES              104
#define IDS_SEND_COMPLETE               105
#define IDS_SEND_INFO                   106
#define IDS_ERR_INFO                    107
#define IDS_GUIDE_BANK                  108
#define IDS_GUIDE_TEMP                  109
#define IDS_GUIDE_COPY                  110
#define IDS_NOTEXIST_BANK0000           111
#define IDS_GUIDE_PLACE_FINGER          112
#define IDS_ENROLL_COMPLETE             113
#define IDS_BANKTEMP_INFO               114
#define IDS_COPY_COMPLETE               115
#define IDS_DEL_COMPLETE_TEMP           116
#define IDS_DEL_COMPLETE_BANK           117
#define IDS_DEL_COMPLETE_ALL            118
#define IDS_GUIDE_DELALL                119
#define IDS_SEND_LED                    120
#define IDS_SEND_LEDCOMPLETE            121
#define IDS_LED_GREEN                   122
#define IDS_LED_RED                     123
#define IDS_LED_GREENRED                124
#define IDS_LED_OFF                     125
#define IDS_SEND_SEC                    126
#define IDS_SEC_LOW                     127
#define IDR_MAINFRAME                   128
#define IDS_SEC_MIDLOW                  128
#define IDS_SEC_MID                     129
#define IDB_BITMAP1                     130
#define IDS_SEC_MIDHIGH                 130
#define IDD_DIALOG_DETAILS              131
#define IDS_SEC_HIGH                    131
#define IDD_DIALOG_TAB0                 132
#define IDS_SEND_BUZ                    132
#define IDD_DIALOG_TAB1                 133
#define IDS_BUZ_ON                      133
#define IDD_DIALOG_TAB2                 134
#define IDS_BUZ_OFF                     134
#define IDS_SEND_VERIF                  135
#define IDS_VERIF_11                    136
#define IDS_VERIF_1N                    137
#define IDS_VERIF_ACBANK                138
#define IDS_VERIF_WTEMP                 139
#define IDS_COPY_TEMPFILE               140
#define IDS_SEND_HWRESET                141
#define IDS_SEND_SCRAMBLE               142
#define IDS_SEND_DEVINFO                143
#define IDS_FW_VERSION                  144
#define IDS_SER_NUMMBER                 145
#define IDS_SND_TSENNOTFY               146
#define IDS_TSENNOTYFY_ENABLE           147
#define IDS_ENROLL_NG                   148
#define IDS_SEND_GETTEMP                149
#define IDS_VERIF_SUCCESS               150
#define IDS_VERIF_NG                    151
#define IDS_BANKINFO                    152
#define IDS_ACROSBKINFO                 153
#define IDS_TEMPFULL                    154
#define IDS_SETTING_END                 155
#define IDS_POLLING_TIMEOUT             156
#define IDS_NON_SELECT                  157
#define IDS_ERR_GENMSG                  158
#define IDS_ERR_G_TRANTOUT              159
#define IDS_ERR_G_READFILE              160
#define IDS_ERR_G_WRITEFILE             161
#define IDS_ERR_G_RECVDATANON           162
#define IDS_ERR_G_TMPFILE_NOTOPEN       163
#define IDS_ERR_G_INVALIDRESP           164
#define IDS_ERR_G_TEMPNON               165
#define IDS_ERR_G_TEMPDELETE            166
#define IDS_ERR_G_TEMPCOPY              167
#define IDC_BUTTON_OPEN                 1000
#define IDC_BUTTON2                     1002
#define IDC_BUTTON_COPY                 1003
#define IDC_BUTTON_SAVE                 1004
#define IDC_BUTTON_DELTEMP              1006
#define IDC_BUTTON_DELBANK              1007
#define IDC_BUTTON_DELALL               1008
#define IDC_BUTTON_ENROLL               1011
#define IDC_BUTTON5                     1018
#define IDC_STATIC_ENROLL               1022
#define IDC_STATIC_SELECT_BANK          1024
#define IDC_STATIC_                     1030
#define IDC_STATIC_FWVER                1030
#define IDC_STATIC_SET_FWVER            1031
#define IDC_STATIC_SERIAL               1032
#define IDC_STATIC_SET_SERIAL           1033
#define IDC_DTAILS_TAB                  1034
#define IDC_LIST_TMPLIST                1040
#define IDC_EDIT_11VERBANK              1041
#define IDC_EDIT_11VERTEMP              1042
#define IDC_EDIT_STARTBANK              1043
#define IDC_STATIC_TLIST                1044
#define IDC_EDIT_ENDBANK                1044
#define IDC_EDIT_DELONE_BANK            1045
#define IDC_STATIC_TEMPS                1045
#define IDC_STATIC_TSSTAT               1046
#define IDC_EDIT_N1BANK                 1046
#define IDC_STATIC_COMMENT              1047
#define IDC_EDIT_DELBANK                1047
#define IDC_STATIC_CGBOX                1048
#define IDC_EDIT_DELONE_TEMP            1048
#define IDC_STATIC_FNAME                1049
#define IDC_BUTTON_MAIN                 1051
#define IDC_COMB_TEMP1                  1052
#define IDC_STATIC_FNAME2               1053
#define IDC_BUTTON_SECLOW               1053
#define IDC_COMB_TEMP2                  1053
#define IDC_STATIC_COPYTEMP             1054
#define IDC_COMB_TEMP3                  1054
#define IDC_STATIC_DELETETMP            1055
#define IDC_COMB_TEMP4                  1055
#define IDC_STATIC_DELETEBANK           1056
#define IDC_COMB_TEMP5                  1056
#define IDC_STATIC_DELETEALL            1057
#define IDC_BUTTON_SECMLOW              1057
#define IDC_COMB_TEMP6                  1057
#define IDC_BUTTON_SECMID               1058
#define IDC_BUTTON_SECMIDHG             1059
#define IDC_BUTTON_SECHIGH              1060
#define IDC_BUTTON_BUZON                1061
#define IDC_BUTTON_BUZOFF               1062
#define IDC_BUTTON_LEDGREEN             1063
#define IDC_BUTTON_LEDRED               1064
#define IDC_BUTTON_LEDGR                1065
#define IDC_BUTTON_LEDOFF               1066
#define IDC_BUTTON20                    1067
#define IDC_STATIC_CTRBUZZER            1068
#define IDC_STATIC_CTRLED               1069
#define IDC_STATIC_SETSECURITY          1070
#define IDC_STATIC_H1ERESET             1071
#define IDC_STATIC_11VER                1072
#define IDC_STATIC_1NVER                1073
#define IDC_STATIC_VERACBANK            1074
#define IDC_STATIC_VERTEMP              1075
#define IDC_COMBO_COMPORT               1076
#define IDC_BUTTON_COMSET               1077
#define IDC_EDIT_COMMENT                1078
#define IDC_EDIT_SST                    1079
#define IDC_BUTTON_11VERIF              1080
#define IDC_BUTTON_1NVERIF              1081
#define IDC_BUTTON_VERIF_AB             1082
#define IDC_BUTTON_VERIFWT              1083
#define IDC_EDIT_ENROLL_BANK            1084
#define IDC_EDIT_ENROLL_TMPNO           1085
#define IDC_EDIT_COPYBANK               1086
#define IDC_EDIT_COPYCOUNT              1087
#define IDC_CHECK_POL                   1088

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
