//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by H2E_SampleApp.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_H2E_SAMPLEAPP_DIALOG        102
#define IDS_ABOUTBOX2                   102
#define IDS_COMOPEN                     103
#define IDS_ERR_COMOPEN                 104
#define IDS_SEND_TEMPLATES              105
#define IDS_SEND_COMPLETE               106
#define IDS_SEND_INFO                   107
#define IDS_ERR_INFO                    108
#define IDS_GUIDE_BANK                  109
#define IDS_GUIDE_TEMP                  110
#define IDS_GUIDE_COPY                  111
#define IDS_APP_NAME                    111
#define IDS_NOTEXIST_BANK0000           112
#define IDS_SETTING_END                 112
#define IDS_GUIDE_PLACE_FINGER          113
#define IDS_ENROLL_COMPLETE             114
#define IDS_BANKTEMP_INFO               115
#define IDS_GROUPTEMP_INFO              115
#define IDS_COPY_COMPLETE               116
#define IDS_DEL_COMPLETE_TEMP           117
#define IDS_DEL_COMPLETE_BANK           118
#define IDS_DEL_COMPLETE_ALL            119
#define IDS_GUIDE_DELALL                120
#define IDS_SEND_LED                    121
#define IDS_SEND_LEDCOMPLETE            122
#define IDS_LED_GREEN                   123
#define IDS_LED_RED                     124
#define IDS_LED_GREENRED                125
#define IDS_LED_OFF                     126
#define IDS_SEND_SEC                    127
#define IDR_MAINFRAME                   128
#define IDS_SEC_LOW                     128
#define IDD_TUCH_DIALOG                 128
#define IDS_SEC_MIDLOW                  129
#define IDS_SEC_MID                     130
#define IDS_SEC_MIDHIGH                 131
#define IDS_SEC_HIGH                    132
#define IDS_SEND_BUZ                    133
#define IDS_BUZ_ON                      134
#define IDS_BUZ_OFF                     135
#define IDS_SEND_VERIF                  136
#define IDS_VERIF_11                    137
#define IDS_VERIF_1N                    138
#define IDS_VERIF_ACBANK                139
#define IDS_VERIF_WTEMP                 140
#define IDS_COPY_TEMPFILE               141
#define IDS_SEND_GETDEVINFO_FW          142
#define IDS_SEND_GETDEVINFO             142
#define IDS_SEND_GETDEVINFO_SL          143
#define IDS_SEND_ENROLL                 144
#define IDS_SEND_DELTEMP                145
#define IDS_SEND_GDELTEMP               146
#define IDS_SEND_DELALLTMP              147
#define IDS_RELEASE_FINGER              148
#define IDS_GUIDE_RELEASE_FINGER        148
#define IDS_SUBID_FVERSION              149
#define IDS_SUBID_SERIAL                150
#define IDS_SEND_GETTEMP_INFO           151
#define IDS_VERIF_COMPLETE              152
#define IDS_VERIF_INFO                  153
#define IDS_DEL_INFO                    154
#define IDS_DEL_INFO2                   155
#define IDS_TEMP_NON                    156
#define IDS_UPLOAD_COMPLETE             157
#define IDS_DOWNLOAD_COMPLETE           158
#define IDS_SEND_WRITE_TEMP             159
#define IDS_SEND_READ_TEMP              160
#define IDS_READ_COMPLETE               161
#define IDS_WRITE_COMPLETE              162
#define IDS_ENROLL_NG                   163
#define IDS_VERIF_SUCCESS               164
#define IDS_VERIF_NG                    165
#define IDS_TEMPFULL                    166
#define IDS_POLLING_TIMEOUT             167
#define IDS_POLLING_TIMEOUT2            168
#define IDC_TOUCH_OUT1                  1000
#define IDC_TOUCH_OUT2                  1001
#define IDC_STATIC_TUCH1                1001
#define IDC_STATIC_TUCH2                1002
#define IDC_BUTTON_DELTEMP              1006
#define IDC_BUTTON_DELGROUP             1007
#define IDC_BUTTON_DELALL               1008
#define IDC_BUTTON_DOWNLOAD             1009
#define IDC_BUTTON_CHECK                1010
#define IDC_BUTTON_UPLOAD               1011
#define IDC_BUTTON_ENROLL               1013
#define IDC_STATIC_ENROLL               1022
#define IDC_STATIC_FWVER                1030
#define IDC_STATIC_SET_FWVER            1031
#define IDC_STATIC_SERIAL               1032
#define IDC_STATIC_SET_SERIAL           1033
#define IDC_LIST_TMPLIST                1040
#define IDC_EDIT_11VERBANK              1041
#define IDC_EDIT_11VERTEMP              1042
#define IDC_EDIT_STARTBANK              1043
#define IDC_STATIC_TLIST                1044
#define IDC_STATIC_TEMPS                1045
#define IDC_EDIT_N1BANK                 1046
#define IDC_STATIC_COMMENT              1047
#define IDC_STATIC_CGBOX                1048
#define IDC_STATIC_FNAME                1049
#define IDC_EDIT_ENDBANK                1050
#define IDC_BUTTON_END                  1051
#define IDC_EDIT_DELONE_BANK            1052
#define IDC_STATIC_FNAME2               1053
#define IDC_EDIT_DELBANK                1054
#define IDC_STATIC_DELETETMP            1055
#define IDC_EDIT_DELONE_TEMP            1056
#define IDC_STATIC_DELETEBANK           1057
#define IDC_STATIC_DELETEALL            1058
#define IDC_STATIC_DELETEALL2           1059
#define IDC_STATIC_DELETEALL3           1060
#define IDC_STATIC_CGBOX2               1061
#define IDC_STATIC_FNAME3               1062
#define IDC_STATIC_FNAME4               1063
#define IDC_STATIC_11VER                1072
#define IDC_STATIC_1NVER                1073
#define IDC_STATIC_VERACBANK            1074
#define IDC_COMBO_COMPORT               1076
#define IDC_BUTTON_COMOPEN              1077
#define IDC_EDIT_COMMENT                1078
#define IDC_COMBO_SPEED                 1079
#define IDC_BUTTON_11VERIF              1080
#define IDC_BUTTON_1NVERIF              1081
#define IDC_BUTTON_VERIF_AB             1082
#define IDC_EDIT_ENROLL_BANK            1084
#define IDC_EDIT_ENROLL_TMPNO           1085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
